# ============================================
# Kustomization for Production Environment
# Applies prod-specific configurations
# ============================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ogscout-prod

# Base resources
resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/hpa.yaml
- ../../base/ingress.yaml

# Common labels for all resources
commonLabels:
  environment: production

# Patches for production environment
patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml

# ConfigMap generator for prod-specific config
configMapGenerator:
- name: ogscout-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - NEXTAUTH_URL=https://ogscout.com

# Image tags (will be updated by CI/CD)
images:
- name: ghcr.io/your-org/ogscout
  newTag: latest
