# ============================================
# Kustomization for Production Environment
# Applies prod-specific configurations
# ============================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ogscout-prod

# Base resources
resources:
  - ../../base

# Use "labels" instead of deprecated "commonLabels"
labels:
  - pairs:
      environment: production

# Use the modern "patches" field instead of deprecated "patchesStrategicMerge"
patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress-patch.yaml

# ConfigMap generator for prod-specific config
configMapGenerator:
  - name: ogscout-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://ogscout.com
      # Public environment variables can be added here if needed
      # Example: - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=your-key-here

# The CI/CD pipeline will dynamically update this image tag using "kustomize edit set image"
images:
  - name: ghcr.io/service-go-repo/ogscout
    newTag: latest
