# ============================================
# ConfigMap for Non-Sensitive Configuration
# Contains environment-specific settings
# ============================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: ogscout-config
  labels:
    app: ogscout
data:
  # Application Settings
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"

  # Next.js Settings
  NEXT_TELEMETRY_DISABLED: "1"

  # MongoDB Connection (non-sensitive parts)
  # Full URI will be constructed using secrets
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "repair-connect"

  # API Configuration
  API_TIMEOUT: "30000"
  API_RATE_LIMIT: "100"
