# ============================================
# Horizontal Pod Autoscaler (HPA)
# Automatically scales pods based on CPU/Memory usage
# ============================================

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ogscout-hpa
  labels:
    app: ogscout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ogscout-app

  # Scaling configuration
  minReplicas: 2
  maxReplicas: 10

  # Metrics for scaling decisions
  metrics:
  # Scale based on CPU usage
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

  # Scale based on Memory usage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min

    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
