# ============================================
# MongoDB Secret Template
# Contains database credentials
# ============================================
#
# IMPORTANT: This is a template. In production, create secrets via:
# kubectl create secret generic mongodb-secret \
#   --from-literal=MONGO_ROOT_USERNAME=admin \
#   --from-literal=MONGO_ROOT_PASSWORD=<strong-password> \
#   --namespace=<namespace>
#
# OR use the workflow to create secrets automatically
# ============================================

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    component: database
type: Opaque
stringData:
  # Default values - CHANGE IN PRODUCTION!
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "changeme123"  # MUST BE CHANGED!
