# ============================================
# Kustomization for Development Environment
# Applies dev-specific configurations
# ============================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ogscout-dev

# Base resources
resources:
- ../../base/configmap.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/hpa.yaml
- ../../base/ingress.yaml

# Common labels for all resources
commonLabels:
  environment: development

# Patches for dev environment
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

# ConfigMap generator for dev-specific config
configMapGenerator:
- name: ogscout-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - NEXTAUTH_URL=https://dev.ogscout.com

# Image tags (will be updated by CI/CD)
images:
- name: ghcr.io/your-org/ogscout
  newTag: latest
