# ============================================
# Kustomization for Development Environment
# Applies dev-specific configurations
# ============================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ogscout-dev

# Base resources
resources:
  - ../../base

# Use "labels" instead of deprecated "commonLabels"
labels:
  - pairs:
      environment: development

# Use the modern "patches" field instead of deprecated "patchesStrategicMerge"
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

# ConfigMap generator for dev-specific config
configMapGenerator:
- name: ogscout-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - NEXTAUTH_URL=https://dev.ogscout.com

# Image tags (will be updated by CI/CD)
images:
  - name: ghcr.io/service-go-repo/ogscout
    newTag: latest
